apiVersion: v1
kind: Pod
metadata:
  labels:
    buld: kaniko
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      command:
        - cat
      tty: true
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 2
          memory: 4Gi
    - name: helm
      image: alpine/helm:3.5.4
      command:
        - cat
      tty: true
  tolerations:
    - key: "nodes-dev"
      operator: "Equal"
      value: "taint"
      effect: "NoSchedule"
    - key: "nodes-qa"
      operator: "Equal"
      value: "taint"
      effect: "NoSchedule"
    - key: "nodes-prod"
      operator: "Equal"
      value: "taint"
      effect: "NoSchedule"