module.exports = {
  publicRuntimeConfig: {
    API_URL: process.env.API_URL,
    SCAN_NETWORK: process.env.SCAN_NETWORK,
    SCAN_NETWORK_ADDRESS: process.env.SCAN_NETWORK_ADDRESS,
    CONTRACT_XBASE: process.env.CONTRACT_XBASE,
    CONTRACT_TOKEN: process.env.CONTRACT_TOKEN,
    CONTRACT_XXX: process.env.CONTRACT_XXX,
    CONTRACT_XGOLD: process.env.CONTRACT_XGOLD,
    CONTRACT_XQORE: process.env.CONTRACT_XQORE,
    ALLOWED_CHAIN_ID: process.env.ALLOWED_CHAIN_ID,
    STAND: process.env.STAND,
    PANCAKE_SWAP_CONTRACT: process.env.PANCAKE_SWAP_CONTRACT,
    CONTRACT_ADDRESS_ROUTER: process.env.CONTRACT_ADDRESS_ROUTER,
    CONTRACT_PANCAKE_EXCHANGE: process.env.CONTRACT_PANCAKE_EXCHANGE,
  },
};
