apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.STAND_NAME }}-main-vs
spec:
  hosts:
  {{- if .Values.HOST_NAME_PROD }}
  - {{ .Values.HOST_NAME_PROD }}
  {{- else }}
  - {{ .Values.HOST_NAME }}
  {{- end }}
  gateways:
  - {{ .Values.STAND_NAME }}-forsage-gateway
  http:
  - name: "front-route"
    match:
      - uri:
          prefix: "/information"
    route:
    - destination:
        host: forsage-busd-frontend
        port:
          number: 3000
    corsPolicy:
      allowOrigins:
      - exact: "*"
      allowMethods:
      - POST
      - GET
      - PUT
      - PATCH
      - POST
      - DELETE
      allowHeaders:
      - X-Requested-With
      - Authorization
      - Application
      - Origin
      - Content-Type
      - Accept
      - Set-Cookie
      - -x-forsage-api-version
      maxAge: 24h
      allowCredentials: true
  - name: "backend-route"
    match:
      - uri:
          prefix: "/api"
      - uri:
          prefix: "/docs"
      - uri:
          regex: ".*info.*"
    route:
      - destination:
          host: backendlaravel-nginx
          port:
            number: 80
    corsPolicy:
      allowOrigins:
        - exact: "*"
      allowMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowHeaders:
        - X-Requested-With
        - Authorization
        - Application
        - Origin
        - Content-Type
        - Accept
        - Set-Cookie
        - Enctype
        - -x-forsage-service
      maxAge: 24h
      allowCredentials: true
  - name: "main-route"
    route:
    - destination:
        host: forsage-busd-frontend
        port:
          number: 3000
    corsPolicy:
      allowOrigins:
      - exact: "*"
      allowMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      allowHeaders:
      - X-Requested-With
      - Authorization
      - Application
      - Origin
      - Content-Type
      - Accept
      - Set-Cookie
      maxAge: 24h
      allowCredentials: true
---
