replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  imagePullSecrets: regcred

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

services:
  nginx:
    type: ClusterIP
    port: 80

resources:
  limits:
    cpu: 200m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 500Mi

affinity: {}

nodeSelector:
  kops.k8s.io/instancegroup: nodes-prod

tolerations:
- key: "nodes-prod"
  operator: "Equal"
  value: "taint"
  effect: "NoSchedule"